In [ ]:
#1D Array

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [9]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
#2D Array

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.6173659 , 0.65666588, 0.04428091, 0.28554623, 0.45510585])

In [30]:
np.random.rand(5,2)

array([[0.96002795, 0.99838606],
       [0.01193641, 0.05152637],
       [0.21423379, 0.7826588 ],
       [0.81982703, 0.59264881],
       [0.09750845, 0.74968374]])

In [35]:
np.random.randn(2,3)

array([[ 0.06963441, -0.88343599,  0.76348108],
       [ 0.89595184, -0.1842474 ,  0.72111858]])

In [39]:
np.random.randint(1,100,10)

array([57, 79, 25, 21,  2, 39, 83, 50, 81, 86])

In [51]:
arr = np.arange(25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr = np.random.randint(0,50,10)

In [45]:
ranarr

array([31, 39, 18, 22,  1, 27, 39, 45, 35,  3])

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr.max()

45

In [56]:
ranarr.min()

1

In [57]:
ranarr

array([31, 39, 18, 22,  1, 27, 39, 45, 35,  3])

In [58]:
# 45 is biggest, and it is positioned as the 7th character
ranarr.argmax()

7

In [59]:
ranarr.argmin()

4

In [60]:
arr.shape

(25,)

In [61]:
arr = arr.reshape(5,5)

In [62]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
arr.shape

(5, 5)

In [64]:
arr.dtype

dtype('int64')

In [65]:
# How to make a reference
from numpy.random import randint

In [66]:
randint(2,10)

5